### ISSUE TITLE
Error fetching configuration, Error: No configuration, error - code: -999

### ISSUE THREAD

**Issue by MoniaL** [mobfox/MFX-iOS-SDK#1]
For over 2 weeks or more I'm trying to contact mobfox in many ways (by email, chat from their website, support tickets) but nobody ever has answered... I'm so frustrated.....
I iplemented the newest SDK but I get errors:

```
Error fetching configuration
Error: No configuration
error - code: -999
```

I belive it has something to do with the note on manual page: https://mobfox.atlassian.net/wiki/spaces/PUMD/pages/1272020993/Objective+C+-+Installation+manual

```
#Note - To enable traffic from your inventories; please contact your assigned account manager and provide the bundle ID and corresponding inventory hashes related to your SDK traffic.
```

as I said I tried to contact my assigned account manager but he never answered. Then I tried to write a support ticket but again nobody ever answered. And later I wrote many messages on mobfox website chat but guess what - nobody ever answered.

So I ended up here, hoping somebody will finally answer my emails/chats/tickets/posts!!!!!!

**Comment by EpicApex** [comment]
Hello Monial,

Please contact support.team@mobfox.com and we will take this from there.

Cheers,
Omri

**Comment by khawaja-salman** [comment]
Can you please provide the solution here because I followed the same manual and getting the same results.

**Comment by MoniaL** [comment]
I gave up using mobfox

**Comment by khawaja-salman** [comment]
> I gave up using mobfox

Thank you so much @MoniaL for the reply. Yeah I can understand.
